name: Python CI

on: [push, pull_request]

jobs:
  build:  # 👈 This is the job name
    runs-on: windows-latest  # 👈 Use "windows-latest" as the valid GitHub runner

    steps:
      - name: Say Hello
        run: echo "test 1"
